---
- name: Creating a copy of parmlib member
  hosts: zxplore
  gather_facts: false
  environment: "{{ environment_vars }}"
  collections:
    - ibm.ibm_zos_core

  tasks:
    - name: "Copy from content to file"
      ibm.ibm_zos_core.zos_copy:
        content: "Hello World"
        dest: /z/z04683/hello_from_GSE
        force: true
