---
- name: Create uss file and copy/encode from controler file
  hosts: zxplore
  gather_facts: false
  environment: "{{ environment_vars }}"
  collections:
    - ibm.ibm_zos_core
  tasks:
    - name: Touch a file
      ansible.builtin.file:
        path: /tmp/ansible_file_from_builtin_file
        state: touch

    - name: Convert file encoding from controller file to USS
      zos_encode:
        src: /tmp/ansible_file_from_builtin_file
        dest: /tmp/ansible_file_from_zos_encode
        encoding:
          from: UTF-8
          to: IBM-1047

    - name: Copy inline content to a a USS file with one space
      zos_copy:
        content: ' '
        dest: /tmp/ansible_file_from_zos_copy
        encoding:
          from: UTF-8
          to: IBM-1047
