---
- name: Allocate dataset
  hosts: zxplore
  gather_facts: false
  environment: "{{ environment_vars }}"
  collections:
    - ibm.ibm_zos_core
  tasks:
    - name: Allocate a dataset on zexplore
      ibm.ibm_zos_core.zos_data_set:
        name: "{{ansible_user}}.ZEXPLORE.DS1"
        type: seq
        state: present    
