---
# Copyright (c) IBM Corporation 2021
# tasks file for query_csi
# LIST HOLDDATA

- hosts: zxplore
  collections:
    - ibm.ibm_zos_core  
  gather_facts: no
  vars:
    ptf: 'HL00008'
    global_csi: 'Z04683.OSHOOLI.GLOBAL.CSI'
    zone: GLOBAL
    list_operands: 'SYSMOD({{ ptf }}) HOLDDATA .' 
    SMPOUT_DATA_SET_NAME: "Z04683.ANSIBLE.SMPOUT"
    SMPLIST_DATA_SET_NAME: "Z04683.ANSIBLE.SMPLIST"
  environment: "{{ environment_vars }}"
  
    
  tasks:
#    - name: "LIST {{ list_operands }} FROM ZONE {{ zone }}"
    - name: SMP/E LIST SYSMOD HOLDDATA
      ibm.ibm_zos_core.zos_mvs_raw:
        pgm: GIMSMP
        auth: "true"
        dds:
          - dd_data_set:
              dd_name: "SMPCSI"
              data_set_name: "{{ global_csi }}"
          - dd_data_set:
              dd_name: "SMPOUT"
              data_set_name: "{{ SMPOUT_DATA_SET_NAME }}"
              disposition: new
              type: seq
              return_content:
                type: text
          - dd_data_set:
              dd_name: "SMPLIST"
              data_set_name: "{{ SMPLIST_DATA_SET_NAME }}"
              disposition: new
              type: seq
              return_content:
                type: text
          - dd_output:
              dd_name: "SYSPRINT"
              return_content:
                type: text
          - dd_input:
              dd_name: "SMPCNTL"
              content:
                - 'SET  BOUNDARY({{ zone }}) .'
                - 'LIST {{ list_operands }}' 
      register: output_rc_0

    - name: print output
      debug:
        msg:
          - "{{ output_rc_0 }}"


#      always:
    - name: delete data sets
      zos_data_set:
        name: "{{ item }}"
        state: absent
      loop:
        - "{{ SMPLIST_DATA_SET_NAME }}"  
        - "{{ SMPOUT_DATA_SET_NAME }}"  
