---
- name: Creating a job from template and submitting it
  hosts: zxplore
  gather_facts: false
  environment: "{{ environment_vars }}"
  collections:
    - ibm.ibm_zos_core
  vars:
    dsname: "Z04683.ANSB.DSN1"
  tasks:
    - name: Prepare our job
      ansible.builtin.template:
        src: job14-2.j2
        dest: ./job14.jcl
      vars:
        datasets_to_be_allocated:
          - ddname: REXX
            dsname: Z04683.ANSB.REXX
          - ddname: COBOL
            dsname: Z04683.ANSB.COBOL
      delegate_to: localhost

    - name: Submit job create
      ibm.ibm_zos_core.zos_job_submit:
        src: ./job14.jcl
        location: local
        encoding:
          from: ISO8859-1
          to: IBM-1047
        wait_time_s: 30
        return_output: true
        max_rc: 0
