---
- name: submit jobs if task absent
  hosts: zxplore
  gather_facts: false
  environment: "{{ environment_vars }}"
  collections:
    - ibm.ibm_zos_core
  tasks:
    - name: "Checking active tasks"
      ibm.ibm_zos_core.zos_operator:
        cmd: D A,L
      register: active_tasks

    - name: Setting variables
      ansible.builtin.set_fact:
        task_to_search: ZWE1AC

    - name: Submitting maintenance jobs
      ibm.ibm_zos_core.zos_job_submit:
        src: "{{ item.dsn }}({{ item.member }})"
        location: data_set
        wait_time_s: 30
        return_output: true
        max_rc: 0
      loop:
        - dsn: Z04683.ANSB.JCL
          member: JOB1
        - dsn: Z04683.ANSB.JCL
          member: JOB2
      when: task_to_search not in active_tasks
      register: submitted_jobs

    - ansible.builtin.debug:
        var: submitted_jobs

