  ---
  - name: Creating a job from template and submitting it
    hosts: zxplore
    gather_facts: false
    environment: "{{ environment_vars }}"
    collections:
      - ibm.ibm_zos_core
    vars:
      dsname: "{{ ansible_user | upper }}.ANSB.DSN1"
    tasks:
      - name: Prepare our job
        ansible.builtin.template:
          src: job14-1.j2
          dest: ./job14.jcl
        delegate_to: localhost

      - name: Submit JCL with use_template
      ibm.ibm_zos_core.zos_job_submit:
        src: "{{playbook_dir}}/templates/job14-1.j2"
        location: LOCAL
        use_template: true
        wait_time_s: 60
        return_output: True
      register: result

