---

- name: sample of issuing MVS command by using a system console
  hosts: zxplore
  collections:
    - ibm.ibm_zos_zosmf
  gather_facts: false
  environment:
    "{{ environment_vars }}"

  vars_prompt:
    - name: zmf_user
      prompt: "Enter your zOSMF username (skip if zmf_crt and zmf_key are supplied)"
      private: no
    - name: zmf_password
      prompt: "Enter your zOSMF password (skip if zmf_crt and zmf_key are supplied)"
      private: yes
  tasks:
    - zmf_authenticate:
        zmf_host: "{{ zmf_host }}"
        zmf_port: "{{ zmf_port }}"
        zmf_user: "{{ zmf_user }}"
        zmf_password: "{{ zmf_password }}"
      register: result_auth
      delegate_to: localhost
    - zmf_console_command:
        zmf_credential: "{{ result_auth }}" # Authentication credentials returned by module zmf_authenticate
        console_cmd: "d iplinfo"
        console_system: "{{ inventory_hostname }}"
        # console_cmdresponse_keyword: "SLP registration initiated" # The keyword that you want to detect in the command response. The module will fail if no specified keywords are detected in neither the command response nor broadcast messages
        # console_cmdresponse_reg: false # Whether console_cmdresponse_keyword represents a regular expression. Default is false
        # console_broadcastmsg_keyword: "started CIM server" # The keyword that you want to detect in broadcast messages. The module will fail if no specified keywords are detected in neither the command response nor broadcast messages
        # console_broadcastmsg_reg: false # Whether console_broadcastmsg_keyword represents a regular expression. Default is false
        # console_broadcastmsg_detect_timeout: 30 # How long, in seconds, the console attempts to detect the value of console_broadcastmsg_keyword in the broadcast messages. Default is 30
        # console_cmdresponse_retrieve_times: 1 # How many times the console attempts to retrieve the command response. Default is 1
        console_save_output_localpath: "/tmp/cmd_output" # The local path on control node where the command response will be saved to
      register: result
      delegate_to: localhost
    - debug: var=result
