###############################################################################
# © Copyright IBM Corporation 2021
###############################################################################

###############################################################################
# This sample playbook demonstrates basic use cases for invoking a REST API
# service, particularly the z/OSMF REST API services.
#
# Usage:
#  ansible-playbook -i <inventory> <playbook>
#
# Example:
#  ansible-playbook -i inventories uri-sample.yml
#
###############################################################################
---
- name: perform various operations with z/OSMF workflows
  hosts: zxplore
  collections:
    - ibm.ibm_zosmf
    - ibm.ibm_zos_core
  gather_facts: false
  environment:
    "{{ environment_vars }}"

  vars:
    
    # Version of z/OSMF used to make REST calls
    ZOSMF_VERSION: "1.0"

    # ***************************************************
    #   Variables for invoking z/OSMF REST API services
    # ***************************************************

    # z/OSMF host and port information
    ZOSMF_HOST: 204.90.115.200
    ZOSMF_PORT: 10443

    # Desired destination folder on target host for holding definition file
    ZOSMF_DEST_FOLDER: /z/znnnnn

    # Credentials to access z/OSMF
    ZOSMF_USER: Znnnnn
    ZOSMF_PASS: ppppppp

    # HLQ to list all datasets
    ZOSMF_HLQ: Znnnnn

  tasks:
    - name: Query list of datasets
      uri:
        url: https://{{ ZOSMF_HOST }}:{{ ZOSMF_PORT }}/zosmf/restfiles/ds?dslevel={{ ZOSMF_HLQ }}.**
        user: "{{ ZOSMF_USER }}"
        password: "{{ ansible_password }}"
        method: GET
        headers:
          Content-Type: application/json
          X-CSRF-ZOSMF-HEADER: required_header
        force_basic_auth: true
        validate_certs: false
        status_code: 200
        return_content: true

      register: zosmf_result
    - name: Response dslist {{ ZOSMF_HLQ }} 
      ansible.builtin.debug:
        msg: "{{ zosmf_result }}"
    
